---
gui:
  nerdFontsVersion: 3
  border: single
  spinner:
    frames:
      - ⠋
      - ⠙
      - ⠹
      - ⠸
      - ⠼
      - ⠴
      - ⠦
      - ⠧
      - ⠇
      - ⠏

git:
  pagers:
    - pager: diff-so-fancy
    - externalDiffCommand: "difft --color=always --display=inline"

keybinding:
  universal:
    copyToClipboard: "y"
    copyFileInfoToClipboard: <c-o>
